name: Build Check

on:
    workflow_dispatch: {}
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

permissions:
    contents: read

jobs:
    build-test:
        if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
        runs-on: 'ubuntu-latest'

        permissions:
            contents: read

        steps:
            - name: Harden the runner (Audit all outbound calls)
              uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
              with:
                  egress-policy: audit

            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  npm ci

            - name: Run Semantic Release
              run: |
                  npm run release:prepare
