name: Build Check

on:
    workflow_dispatch: {}
    pull_request:
        types: [opened, synchronize, reopened, ready_for_review]

jobs:
    build-test:
        if: ${{ !startsWith(github.event.head_commit.message, 'chore(release):') }}
        runs-on: 'ubuntu-latest'

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true

            - uses: actions/setup-node@v4
              with:
                  node-version-file: .nvmrc
                  cache: 'npm'

            - name: Install dependencies
              run: |
                  npm install

            - name: Run Semantic Release
              run: |
                  npm run release:prepare
